project:
  render:
    - About.qmd
    - BibTex Data Import.qmd
    - Data Cleaning.qmd
    - Word Clouds.qmd
    - Bibliometric Analysis.qmd
    - Network Attributes and Visualisations.qmd
  type: website
  output-dir: docs
  
website:
  title: "Open Science Northumbria"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Main"
        contents:
          - About.qmd
          - BibTex Data Import.qmd
          - Data Cleaning.qmd
          - Word Clouds.qmd
          - Bibliometric Analysis.qmd
          - Network Attributes and Visualisations.qmd
          - PLOS and OSF.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

